require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11'

target 'goppomobile' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
  
  pod 'ReactNativeIncallManager', :path => '../node_modules/react-native-incall-manager'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  target 'goppomobileTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'goppomobile-tvOS' do
  # Pods for goppomobile-tvOS

  target 'goppomobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
